buld:
	pnpm run build
install:
	rm -rf node_modules && pnpm cache delete && pnpm i 
link:
	npm link

linkc:
	npm link 
	

sync_api:
	pnpm cache delete && pnpm add @buf/ahmeddarwish_devkit-api.bufbuild_es@${V}

